import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";
import SideNav from "./components/SideNav";

const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  // You can specify weight if needed
  // weight: ['400', '500', '700'],
  // You can also specify display style
  // display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${instrumentSans.className}`}>
        <SideNav/>
        <div className="ml-[20%]">
        {children}
        </div>
       </body>
    </html>
  );
}